$color = rgba(36, 36, 36, 1)
$inner_color = rgba(36, 36, 36, 0.66)
$outer_color = rgba(97, 175, 239, 1)
$font_color = rgba(171, 178, 191, 1)
$placeholder_color = rgba(171, 178, 191, 0.7)
$check_color = rgba(86, 182, 194, 1)
